# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Helvetic Resume
description: A bold typographic theme inspired by Swiss design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: helvetic-resume # the GitHub repo name for your project
github_username: hipervincle
user_name: Hipervincle

# Optional social links, you can choose from the following options:
# linkedin, bluesky, x (twitter), instagram, medium, or dribbble. Just add
# the name of the media + _username e.g. medium_username and then add your user name
# to make it appear on the page
user_email: user@hipervincle.com

linkedin_username: hipervincle
bluesky_username: hipervincle.bsky.social
medium_username: hipervincle

include: ["_pages"]
exclude: ["scripts"]
permalink: /:title/

# Build settings
markdown: kramdown

# Remote settings
repository: broccolini/swiss
livereload: true
port: 4000

plugins:
  - jekyll-polyglot
  - jekyll-redirect-from
  - jekyll-date-localization
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-octicons

redirect_from:
  json: false

jekyll-minifier:
  uglifier_args:
    harmony: true

languages: ["en", "ca", "es", "it"]
langsep: ·
default_lang: en
exclude_from_localization: ["javascript", "images", "css", "public", "sitemap", "assets"]
parallel_localization: false
lang_from_path: true